### ISSUE TITLE
ZJIT: objtostring miscompile since #17499: Integer where a Symbol is expected

### ISSUE THREAD

**Issue by sampokuokkanen** [Shopify/ruby#1001]
## Summary
ruby-head + ZJIT crashes booting a Rails app during eager-load:
```
undefined method 'to_sym' for an instance of Integer (NoMethodError)
  activerecord-8.1.3/.../builder/collection_association.rb:33
      callback_values = Array(options[callback_name.to_sym])
```
`callback_name` iterates `[:before_add, :after_add, :before_remove, :after_remove]`, so it is always a Symbol. `RUBY_ZJIT_ENABLE=0` boots fine; YJIT is off.

## Bisected
First bad commit: [`6803354732`](https://github.com/ruby/ruby/commit/680335473282a1f8c7851efb37b15ca5c94b6738) "ZJIT: Move objtostring specialization to HIR build" (ruby/ruby#17499). Its parent [`0a40bb7d0f`](https://github.com/ruby/ruby/commit/0a40bb7d0f51569054bc698dab1ac9abbd09e370) boots fine. Bisected across the 06-22..06-29 nightlies, confirmed with from-source builds either side of #17499.

## Mechanism
The method interpolates `callback_name`, then calls `to_sym` on it:
```ruby
full = "#{callback_name}_for_#{name}"   # objtostring on callback_name
Array(options[callback_name.to_sym])    # callback_name now read as Integer
```

## Repro
https://github.com/sampokuokkanen/zjit-rails-eager-load-repro

Could not get it to reproduce on a clean app with only a few models, so I had to distill the production app to the repro app. 

## Environment
`ruby 4.1.0dev (2026-06-29 master 7402021a4a) +ZJIT +PRISM [aarch64-linux]`; ZJIT on, YJIT off, `RUBYOPT=--enable-frozen-string-literal` (not required to trigger); activerecord 8.1.3.

**Comment by tekknolagi** [comment]
Hmm. Thanks for the report. Going to try and minimize this.

**Comment by tekknolagi** [comment]
Are you either willing to either a) hop on a call to try and reproduce on your end or b) asynchronously golf this down to a self-contained (ideally no-dependency) repro?

**Comment by sampokuokkanen** [comment]
Sorry for taking so long, but I confirmed that this was fixed. Thanks! 

Seems to have been fixed by https://github.com/ruby/ruby/pull/17417 (or at least in something that landed on that same day in 2026-07-07, since 2026-07-06 nightly still has the bug).
